spring:
  config:
    import: optional:file:.env.properties
  datasource:
    url: jdbc:sqlite:./data/app.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    url: jdbc:sqlite:./data/app.db
    user:
    password:
    locations: classpath:/db/migration
    enabled: true
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        base-url: ${OPENAI_API_BASE_URL}
        options:
          model: ${MODEL_NAME}
          temperature: 0.7
  embedding:
    service:
      url: ${TEI_URL}
      model: jinaai/jina-embeddings-v2-small-en
      

server:
  port: 8081

logging:
  level:
    com.javallm.controllers: DEBUG
    # Add these two lines for detailed WebClient/Reactor Netty logging:
    reactor.netty.http.client: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG


milvus:
  uri: ${MILVUS_URI}  # default
  token: root:Milvus  # or use username/password separately
  db-name: micla    # optional
  secure: false       # set to true for HTTPS
  connect-timeout-ms: 10000
  keep-alive-time-ms: 55000
  keep-alive-timeout-ms: 20000